[tool.pylint.master]
exit-zero = true
errors-only = true
output-format = "colorized"
diasable = ["E1123","E1120"]

[tool.pytest.ini_options]
testpaths = ['src/qibolab/']
addopts = " --cov=qibolab --cov-report=xml -m 'not qpu'"
