name: tiiq_single_qubit_diagnostics
description: Settings for diagnostic sweeps.

resonator_spectroscopy:
  lowres_width: 30e6
  lowres_step: 2e6
  highres_width: 5e6
  highres_step: 0.2e6
  precision_width: 2e6
  precision_step: 0.02e6

resonator_spectroscopy_shifted:
  lowres_width: 30e6
  lowres_step: 2e6,
  highres_width: 1e6
  highres_step: 0.2e6
  precision_width: 0.5e6
  precision_step: 0.02e6

punchout:
  precision_width: 25e6
  precision_step: 0.5e6

qubit_spectroscopy:
  fast_start: -500e6
  fast_end: 300e6
  fast_step: 2e6
  precision_start: -30e6
  precision_end: 30e6
  precision_step: 0.5e6

t1:
  delay_before_readout_start: 0
  delay_before_readout_end: 4500
  delay_before_readout_step: 30

ramsey:
  start_start: 4
  start_end: 1000
  start_step: 4

spin_echo:
  start_start: 4
  start_end: 500
  start_step: 10

spin_echo_3pulses": 
  start_start: 4
  start_end: 500
  start_step: 10
