# Test Qibolab Rust API
name: Rust API

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Prepare virtual environment
        run: |
          python -m venv env
          pip install .
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check and lint
        working-directory: crate
        run: |
          cargo check
          cargo clippy --all-targets
      - name: Set Python path
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          PYTHONPATH=$(realpath ../env/lib/python3.10/site-packages/):$PYTHONPATH
          PYTHONPATH=$(realpath ../src/):$PYTHONPATH
          echo "PYTHONPATH=$PYTHONPATH" >> "$GITHUB_ENV"
      - name: Build & run example
        working-directory: crate
        run: |
          cargo run --example example
