# A single CI script with github workflow
name: Tests on saadiyat

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/qiboteam/qibo
        pip install .[tiiq,docs]
    - name: Test with pytest core
      run: |
        srun -p qpu5q pytest --pyargs qibolab
